### PR TITLE
Added .so file while initlizing JNIKiwix class which we have missed

### LINKED ISSUE #39: We have missed to load some `.so` file while initlizing the `JNIKiwix` class
We have missed loading `kiwix_wrapper` and `zim_wrapper` in JNIKiwix class.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #39

### CODE REVIEW

**Comment by mgautierfr** [comment]
I wonder if we could have a static block to initialize this. This way you wouldn't have to call `JNIKiwix()` at all.

**Comment by MohitMaliFtechiz** [comment]
> I wonder if we could have a static block to initialize this. This way you wouldn't have to call JNIKiwix() at all.

We can directly load these `.so` files into Android code as mentioned below
Screenshot from 2023-07-13 18-55-32

For making the static block:

Relinker needs the Android context to load the `.so` files, so we need to provide the context to it, for this reason, it has done this way.

**Comment by mgautierfr** [comment]
> Relinker needs the Android context to load the .so files, so we need to provide the context to it, for this reason, it has done this way.

Indeed.

> As we can do this on the Android side, we can manage the loading of the bindings on the Android side.

Are you saying that we should remove `JNIKiwix` function from the wrapper ? You will doing it on caller (android, test) side ?

**Comment by MohitMaliFtechiz** [comment]
> Are you saying that we should remove JNIKiwix function from the wrapper ? You will doing it on caller (android, test) side ?

@mgautierfr, Yes we can directly load the `.so` files of libkiwix in Android code with `relinker` as mentioned in the above screenshot.

**Comment by kelson42** [comment]
Sorry for jumping here, but this is the role of the library to handle all these .so details. Library should just work when imported in kiwix-android.

**Review by mgautierfr — APPROVED** [review]

**Pull request merged**
