### PR TITLE
Allow `zim::Archive` to be created with a set of File descriptor.

### PR DESCRIPTION
**Pull request by mgautierfr**
This PR is in Draft as it wrap a feature in libzim not yet released.
Once new libzim is released, we have still have to change gradle script to use it and then we should be good.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz I have rebased the PR. It seems it should work. Would you be able to give a try to the new primitive to see if it does the job correctly for Kiwix Android?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz I have rebased the PR. It seems it should work. Would you be able to give a try to the new primitive to see if it does the job correctly for Kiwix Android?

@kelson42 Sure. But here is a compilation error with this new feature of libzim, we first have to fix this issue.

**Comment by mgautierfr** [comment]
Thanks for your fix @MohitMaliFtechiz

I have update the PR with fix (including yours) and tests. Should be good.
Please review (and understand how to use 🙂)

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr Thanks for fixing the remaining part and for adding the test cases. I have tested this libzim feature and it is working in kiwix android, libzim able to load the zim file with list of fd.

**Pull request merged**
