### PR TITLE
Build libkiwix aar file

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**

### CODE REVIEW

**Comment by mgautierfr** [comment]
You PR is still in draft but I have few comments anyway:
- The files in android-kiwix-lib-publisher/kiwixLibAndroid/src/main/java/org/kiwix/kiwixlib are already in `src/wrapper/java/org/kiwix/kiwixlib`. We should not duplicate them (use them where they are or move them)
- android-kiwix-lib-publisher is probably not a right name (and not a place to put the source). It was a subdirectory in libkiwix as we were needing a android project to build the aar and we didn't want to merge it with the "classic" cpp project. But now we don't need that. `java-libkiwix` should be a android project, we should move the project files in `android-kiwix-lib-publisher` in the root directory (and so we would have source in `src` directory)
- Generated files (`*.so` and `*.arr`) must not be versionned in the repository

**Comment by kelson42** [comment]
@MohitMaliDeveloper What is the status here (done and still to do)?

**Comment by kelson42** [comment]
@MohitMaliDeveloper It is important we achieve first with this PR to:
* Compile manually the `.aar` (for one architecture)
* be able to load it in an Android app and run one of the method (open ZIM file for example)
* The two steps above are documented in the `README.md`

Once this is done, then we should review/merge this PR. The whole machinery to build/test/publish the JNI automatically (CI/CD) should be done in an other PR(s)

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I am closing this PR , it was to build .aar file for target 10.1.1, since we now already working on latest libkiwix 12 so this one is not needed. 

https://github.com/kiwix/java-libkiwix/pull/20

**Pull request closed without merging**
