### PR TITLE
Move Java  files into separate repo

### PR DESCRIPTION
**Pull request by gouri-panda**
Moved Android Specific Java native files and CPP files from [kiwix-lib](https://github.com/gouri-panda/kiwix-lib)

Imported folders:
[Android-kiwix-lib-publisher](https://github.com/kiwix/libkiwix/tree/master/android-kiwix-lib-publisher)
[src/wrapper/java](https://github.com/kiwix/libkiwix/tree/master/src/wrapper/java)

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Can you please add a PR description?

**Comment by gouri-panda** [comment]
@kelson42 Is there any file should I add except the README.md  file and the .github folder?

**Comment by kelson42** [comment]
Depends what you want to achieve... but at least these one yes.

**Comment by gouri-panda** [comment]
>Depends what you want to achieve... 

A successful build artifact that we can upload to maven central.

>Copy the .github from libkiwix and remove the workflows.

👍

**Comment by kelson42** [comment]
@gouri-panda How do you plan to build the jni package because you don't have the libkiwix in the repo. Anymore?

**Comment by gouri-panda** [comment]
@kelson42 I'm not familiar with how `libkiwix` builds the library for android. Can we do this here also?

**Comment by kelson42** [comment]
@gouri-panda I don't think this is a good idea to do this in this PR. But we need to know how the java binding will be compiled. I'm not an expert, but either we put `openzim/libkiwix` as a git submodule and we compile in a similar manner like done in `kiwix/kiwix-build` or like for our other binding, we publish binary version of libkiwix for Android and they are downloaded here by the build process.

**Comment by mgautierfr** [comment]
@gouri-panda How did you create those commits ?
I suppose with some kind of `git filter-branch`. It would be nice to have the command you've used. It is somehow useless to review the commits themselves.
(I'm not even sure we need the history here, for example, a lot of commit are useless (new version xxxx))

I agree with @kelson42 : it is not this PR to add the build system, but it would be nice (here or somewhere else) to know what is the plan.
Either, this repository also build libkiwix (with all its dependencies, which could be difficult) or we make kiwix-build publish build libraries for android arch and this repository "just" download, build the wrapper part and package everything.

**Comment by gouri-panda** [comment]
@kelson42 Sorry for the late reply! I was caught doing in UI of `kiwix-android`. 
>But we need to know how the java binding will be compiled.

In build-in android JNI it automatically builds .h file. If not it doesn't compile.

In outside JNI I do with this 

```
javac -h . <File Name>
```

 >I suppose with some kind of `git filter-branch`.

@mgautierfr  yes!

>(I'm not even sure we need the history here, for example, a lot of commit are useless (new version xxxx))

Do you want to delete it?
>Either, this repository also build libkiwix (with all its dependencies, which could be difficult) or we make kiwix-build publish build libraries for android arch and this repository "just" download, build the wrapper part and package everything.

@mgautierfr Options 2 sounds good! although I'm not familiar with `kiwix-build` how to do with this

**Comment by mgautierfr** [comment]
> Do you want to delete it?

Maybe not delete all commits. But curating a bit by hand the history to just have the commit that "really" change something on the wrapper side.
Can you add the "git filter-branch" command you've used in the PR description ?

> @mgautierfr Options 2 sounds good! although I'm not familiar with kiwix-build how to do with this
Edit :-
@mgautierfr How much time it will take to complete?

As explain in this comment https://github.com/kiwix/kiwix-tools/issues/464#issuecomment-862420721 publish .so can be problematic.
And as we will drop the the libzim wrapper in libkiwix (https://github.com/kiwix/libkiwix/issues/430), the java wrapper will have at a moment to wrap libkiwix and libzim. We will have to publish two different .so and use it in java-libkiwix (or we create a java-libzim ?)
We may need to use the first option instead. 

---

Anyway, for this PR, it would be nice to have a bit cleanup of the git history but there is nothing to say on the code. It already have been review elsewhere and we know that this first PR will not be functional and we need a base to work on.

Please, cleanup the history, document it in the PR description and we will merge.

**Review by mgautierfr — COMMENTED** [review]
I've made a global review (not commit by commit).
I've not review cpp/h/java files coming from libkiwix repository.

My main comment is : Do we really need to version `kiwixLibAndroid/.cxx` directory ? It seems to be a cache directory.

**Comment by gouri-panda** [comment]
@mgautierfr I'm supposed to clean that in git folder. Thanks I'll do that.

**Pull request closed without merging**
