### PR TITLE
Added support for SDK 34.

### LINKED ISSUE #90: Support and test against SDK 34
Version of Kiwix Android `3.11.0` should introduce support of SDK 34/Android 14. Java libkiwix been a dependence, this is essential that the support is tested here first.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #90 

* Upgraded the Gradle to support the Android 14.
* Made the changes in code to adapt the new gradle.
* Rectify the deprecated code that is not working in the new version of Gradle.
* Upgraded the minimum SDK version to 24.
* Upgraded the `io.github.gradle-nexus:publish-plugin` to `2.0.0`.
* Upgraded the `org.jetbrains.kotlin:kotlin-gradle-plugin` to `1.9.20`.
* Enabled the lint in our project to avoid potential errors. The lint will automatically fail the CI when compiling the project if there is any error in project.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz All checkd pass, ready to merge?

**Comment by kelson42** [comment]
@MohitMaliFtechiz BTW what the diadvantage if we keep 24 as minimum?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz BTW what the diadvantage if we keep 24 as minimum?

There is no any disadvantage to keeping the 24 as the minimum API level. I have changed the minimum API level to 24.

>  Please also have a look to CI log there is far too many errors and warnings ro my taste.

@kelson42 I have fixed the [warnings](https://github.com/kiwix/java-libkiwix/actions/runs/9061905498/job/24894642374?pr=97#step:4:36) reported by the gradle. Apart from these gradle warnings, there are now `cpp` deprecations warnings showing on the CI logs. I think @mgautierfr better know about this, maybe these are necessary for compiling. However, we have the ticket for these warnings https://github.com/kiwix/java-libkiwix/issues/92, so we can move forward with this PR.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please configure that gradle/tests to fail if we have exceptions in CI?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can you please configure that gradle/tests to fail if we have exceptions in CI?

@kelson42 You mean warnings(Right)? since grade automatically fails the task when there is an error. We can add the `lint` here which checks the project's errors. Apart from this,  should we also fail the build when there is a deprecation warning in the `cpp` code? since lint can't directly check the cpp code.

**Comment by kelson42** [comment]
No, I mean java exceptions

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can you please configure that gradle/tests to fail if we have exceptions in CI?
 No, I mean java exceptions

@kelson42 I have added the lint to our project which will fail the CI if any potential error is detected(e.g. gradle and code-related errors).

**Pull request merged**
