### PR TITLE
Release 1.0.2

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr I have tried to remove getSize() to support latest version of libzim, but it seems we have other problems. Could you please have a look please?

**Comment by mgautierfr** [comment]
@MohitMaliDeveloper, The CI is failing at `Install dependencies` step. The error message is 
```
This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
```

Then a backtrace about `33x` not being a number (I agree with that, but don't get from where `33x` comes from). And then plenty of other error message (I let you read them at https://github.com/kiwix/java-libkiwix/actions/runs/7232262963/job/20270039324)

Do you have an idea ?

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr CI is failing on `compile project`, let me check what going on here.

**Comment by mgautierfr** [comment]
The CI is failing of the `compile project`, but with `make[2]: *** No rule to make target 'libkiwix.so', needed by 'libkiwix_wrapper.so'.  Stop.` (line 239).

This is because the `Install Dependencies` has failed (without being an error to stop the CI, which is another problem).

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr Thanks this is the problem with the version of `libkiwix` we have put here `13.0.0-1`. This version archive is available on the https://download.kiwix.org/release/libkiwix/. But internally it has version `13.0.0` as shown in the below image. I think this is obvious because libkiwix has not any release of `13.0.0-1` that why inside the folder it has the `13.0.0` version.

Screenshot from 2024-01-18 18-03-39


> This is because the Install Dependencies has failed (without being an error to stop the CI, which is another problem).

Thanks, I have improved this now CI is failing on the `Install Dependencies` task with error message, see https://github.com/kiwix/java-libkiwix/actions/runs/7570603587/job/20616281022?pr=79#step:4:3514.

**Comment by mgautierfr** [comment]
Version `13.0.0-1` means it is the second build (the first one being `13.0.0`) of the release `13.0.0`. We do this when we change the dependencies (for example, libzim) but we don't change the release of the project (libkiwix).

We should use the `-n` to download the archive but don't use it once we have the archive as internal files inside it will not have it.

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr Thanks, I was not aware of this. Now I understand this properly, I am making changes according to this.

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr I have modified the code to adapt this change, and updated the libkiwix version to `13.0.0-1`.

**Comment by mgautierfr** [comment]
Thanks for the fix !

**Pull request merged**
