### PR TITLE
Better testing (coverage)

### PR DESCRIPTION
**Pull request by mgautierfr**
Jacoco don't track native methods, so our code coverage don't
include all the native methods, and it is exactly want we want to check.

By introducing a test package wrapping all native methods with a small
java function, we have the coverage of the wrapping methods.

### CODE REVIEW

**Comment by mgautierfr** [comment]
This PR doesn't had exhaustive tests, but "fix" the test coverage feature.
From now one, codecov will correctly report coverage (and improvement of the coverage)

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@mgautierfr, thank you for fixing the code coverage. The code looks good, but I wanted to bring up a suggestion regarding our test cases. Since we have already created test classes, it would be more appropriate to utilize these classes instead of directly using the `Archive` in `testBookmark()` and `testServer()`.

https://github.com/kiwix/java-libkiwix/blob/7c7f56d0de389a7c2aa8ec8d3590d406b860ef0a/lib/src/test/test.java#L138

https://github.com/kiwix/java-libkiwix/blob/7c7f56d0de389a7c2aa8ec8d3590d406b860ef0a/lib/src/test/test.java#L151

**Comment by mgautierfr** [comment]
That's the plan, but we cannot for now.
The archive is passed to `Book.update` and it takes a `Archive`.

We should continue the current work and "clone" all the classes in `ork.kiwix.test` to have a full coverage reporting and then extend all tests.

**Comment by MohitMaliFtechiz** [comment]
> This is done now.

@mgautierfr, Thanks, it looks good now.

> We should continue the current work and "clone" all the classes in ork.kiwix.test to have a full coverage reporting and then extend all tests.

Now only Searcher is left to move in the test package. 
Are you planning to re-enable `Searcher` related test in this PR?

**Comment by mgautierfr** [comment]
> Are you planning to re-enable Searcher related test in this PR?

No, it is not necessary to this PR. And it is better to have small PR.

**Review by MohitMaliFtechiz — APPROVED** [review]

**Pull request merged**
