### PR TITLE
Use libzim 9.2.0

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr @MohitMaliFtechiz CI does not pass anymore with just latest libzim... but no clue why?!

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @mgautierfr There is a `FATAL` exception detected by the `JRE` while running the test cases with the latest libzim.

```kotlin
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3dc637a4bc, pid=30864, tid=30867
#
# JRE version: OpenJDK Runtime Environment (11.0.22+7) (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libkiwix.so+0x57a4bc]  zim::DirectDirentAccessor::getDirent(zim::entry_index_t) const+0x6c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/acerpc/Desktop/java-libkiwix/lib/src/test/core.30864)
#
# An error report file with more information is saved as:
# /home/acerpc/Desktop/java-libkiwix/lib/src/test/hs_err_pid30864.log
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Full logs: [hs_err_pid30864.log](https://github.com/kiwix/java-libkiwix/files/15047245/hs_err_pid30864.log)

Mainly it is failing on the `book.update` method.

```kotlin
j  org.kiwix.libkiwix.Book.update(Lorg/kiwix/libzim/Archive;)V+0
j  org.kiwix.test.libkiwix.TestBook.update(Lorg/kiwix/test/libzim/TestArchive;)V+14
```

If we comment that code then the test cases are passing.

Screenshot from 2024-04-20 12-57-48

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you for the investigation. Looks like a bug in the `libkiwix`... although we use the very same version of `libkiwix`. Kind of lost. @mgautierfr Can you please analyse (and fix)?

**Comment by kelson42** [comment]
It seems that using the latest build of libkiwix has fixed the problem, then merging.

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @mgautierfr The error was encountering due to we were using the libkiwix `13.1.0` with libzim `9.2.0`, but libzim `9.2.0` requires the libkiwix `13.1.0-1`.

**Pull request merged**
